# Generated by Django 4.2.11 on 2026-01-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_manager', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='personal_email',
            new_name='email',
        ),
    ]
