# Generated by Django 4.2.11 on 2026-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_manager', '0003_rename_personal_email_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='at_post_of_duty',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='kath_staff_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='payroll_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category_of_profession',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Nursing', 'Nursing'), ('Allied Health', 'Allied Health'), ('Administrative', 'Administrative'), ('Support Staff', 'Support Staff')], max_length=100),
        ),
    ]
